### ISSUE TITLE
CastManager doesn't allow to access VideoCastManager object

### ISSUE THREAD

**Issue by outlying** [jwplayer/jwplayer-sdk-android-demo#10]
Current CastManager delegates only some methods. But I cannot add MiniController because the proper method is not visible.

This is a very limiting approach. 

In case someone here would like to do that, there is small hack to access VideoCastManager, all you have to do is just add this file to your code:

```
package com.longtailvideo.jwplayer.cast;

import com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager;

public class BehHacker {

    public static VideoCastManager getVideoCastManager(){
        return CastManager.getInstance().a;
    }
}
```

Keep in mind, you cannot change package. Luckily CastManager field that holds VideoCastManager has default visibility.

**Comment by GMSyrimis** [comment]
Closing thread as it's fairly old
