### ISSUE TITLE
Demo is crashing

### ISSUE THREAD

**Issue by ekamsoftwares-india** [jwplayer/jwplayer-sdk-android-demo#106]
Hi, I tried to run the demo, but it's crashing on start. Please check screenshot here: http://prntscr.com/ya0f9g

**Comment by GMSyrimis** [comment]
If you haven't resolved the issue yet, please contact support. They can help troubleshoot the issue. From the looks of it, you should open the layout XML and make sure you are importing the correct View for the version of the SDK you are using.
