### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by MIF50** [jwplayer/jwplayer-sdk-android-demo#109]
//TODO:- JW Player
    implementation 'com.longtailvideo.jwplayer:jwplayer-core:3.19.3'
    implementation 'com.longtailvideo.jwplayer:jwplayer-common:3.19.3'
    implementation 'com.longtailvideo.jwplayer:jwplayer-chromecast:3.19.3'

   //TODO:- Exoplayer
   implementation 'com.google.android.exoplayer:exoplayer-core:2.13.3'
    implementation 'com.google.android.exoplayer:exoplayer-dash:2.13.3'
    implementation 'com.google.android.exoplayer:exoplayer-hls:2.13.3'
    implementation 'com.google.android.exoplayer:exoplayer-smoothstreaming:2.13.3'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.13.3'
    implementation 'com.google.android.exoplayer:extension-ima:2.13.3'
    implementation 'com.github.norulab:android-exoplayer-fullscreen:1.2.1'

I got this crash 
java.lang.NoSuchMethodError: No direct method <init>(Lcom/google/android/exoplayer2/trackselection/TrackSelection$Factory;)V in class Lcom/google/android/exoplayer2/trackselection/DefaultTrackSelector; or its super classes (declaration of 'com.google.android.exoplayer2.trackselection.DefaultTrackSelector' appears in /data/app/~~c1NLZSasExDoteahTtBbOQ==/com.timeviewer.tv-dzpHvydn1EWb-BBjhjuA0Q==/base.apk!classes2.dex)

**Comment by mariosampaioneto** [comment]
Same problem here. 

JWPlayer internally uses exoplayer version 2.10.6. 
There are some significant code changes between exoplayer 2.10.6 and 2.13.3.

**Comment by GMSyrimis** [comment]
If you haven't resolved the issue yet, please contact support. They can help troubleshoot the issue.
