### ISSUE TITLE
Question : VR and 360 video support

### ISSUE THREAD

**Issue by stephen1706** [jwplayer/jwplayer-sdk-android-demo#11]
Is the VR and 360 video is supported automatically by the player? because i can't find the 360 video specific player part in the documentation. Thanks.

**Comment by RikHeijdens** [comment]
Hi @stephen1706, 

We are currently working on native 360 video SDKs.
Please contact your sales representative for more information.

Thanks

**Comment by josiekeller** [comment]
Hi @stephen1706,

Wanted to give you an update. VR and 360 video are supported using our VR plugin for web and VR SDKs for Android and iOS. There's a demo available at https://developer.jwplayer.com/jw-player/demos/innovation/360-video/.
