### ISSUE TITLE
Does JW player v4 Support WebVTT Subtitle?

### ISSUE THREAD

**Issue by pavan555** [jwplayer/jwplayer-sdk-android-demo#111]
I am using jw player v4 , i think this is awesome, but there is some feature missing.
captions are not working with webvtt or srt in v4 showing error invalid index/ invalid timing.
but it works well with v3 of jwplayer.

**Comment by GMSyrimis** [comment]
If you haven't already resolved the issue, please contact support. They'll help you troubleshoot the issue. V4 does support WebVTT and SRT captions.
