### ISSUE TITLE
Please help me to customise logo of JWPlayer

### ISSUE THREAD

**Issue by daliborristic883** [jwplayer/jwplayer-sdk-android-demo#120]
iOS JWPlayer supports `JWLogoBuilder` to make customised logo.
But I couldn't find to do this on Android.
Can you please help me how to use customised log on Android JWPlayer?

Thank you.

---- JWPlayer Version ----
4.5.0

**Comment by Jmilham21** [comment]
Hello, thank you for raising this issue. Though this may have been a valid issue, JW Player does not actively monitor this repository for reported issues. We require you to create a ticket following these [guidelines](https://docs.jwplayer.com/players/docs/android-troubleshooting#submit-a-support-ticket). 

For this particular issue, this feature has been added in recent versions. Please refer to our [documentation](https://docs.jwplayer.com/players/docs/android-customize-the-appearance-of-the-player#add-a-branding-image).
