### ISSUE TITLE
Video keeps playing when JWPlayerSupportFragment is detached from activity

### ISSUE THREAD

**Issue by katjarutnik** [jwplayer/jwplayer-sdk-android-demo#122]
Issue probably easily reproducible on all devices, I tested on:
- Pixel 5 running Android 12
- Lenovo A2010 running Android 5.1

Steps to reproduce:
- set JWPlayerFragmentExample.java as the launcher activity in AndroidManifest.xml
- modify JWPlayerFragmentExample.java like:
  - make FragmentManager fm; an instance variable,
  - just for testing purposes to remove fragment from activity, change onOptionsItemSelected function like:
```
@Override
public boolean onOptionsItemSelected(MenuItem item) {
  switch (item.getItemId()) {
	case R.id.switch_to_view:
		fm.beginTransaction().remove(mPlayerFragment).commit();
	default:
		return super.onOptionsItemSelected(item);
  }
}
```
- run app
- play video
- click options (three vertical dots on top right)
- click JWPlayerView Example

- expected result: fragment is removed and any instance of jwplayer is deleted, video stops playing
- actual result: fragment is removed but audio from video continues to play

**Comment by Jmilham21** [comment]
Hello, thank you for raising this issue. Though this may have been a valid issue, JW Player does not actively monitor this repository for reported issues. We require you to create a ticket following these [guidelines](https://docs.jwplayer.com/players/docs/android-troubleshooting#submit-a-support-ticket).
