### ISSUE TITLE
NoMethodFound Exception in JWPlayer

### ISSUE THREAD

**Issue by YogeshSinghPathania** [jwplayer/jwplayer-sdk-android-demo#123]
Hi Im using JWPlayer 4.7V(2.18.1) where you upgrade the player. But  still im facing the issue of 2.16.1 There is a method setDrmSessionManager  that is removed by exoplayer . According to the [Exoplayer/RELEASENOTES](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md), setDrmSessionManager was removed in Exoplayer version 2.17.0. It was labeled as deprecated previously to that.Now we are using setDrmSessionManagerProvider. Im facing the issue due to this when i play any video. 
In your demo you also using 2.16.1. Please let me know what should i do now?

More detail you can check this link-https://github.com/google/ExoPlayer/issues/10956

**Comment by YogeshSinghPathania** [comment]
@johnluther @9ae @polishmatt @MaxMikheyenko can you Please look into this

**Comment by YogeshSinghPathania** [comment]
Anyone is here?

**Comment by Jmilham21** [comment]
Hello, thank you for raising this issue. Though this may have been a valid issue, JW Player does not actively monitor this repository for reported issues. We require you to create a ticket following these [guidelines](https://docs.jwplayer.com/players/docs/android-troubleshooting#submit-a-support-ticket).
