### ISSUE TITLE
Listener for built-in controls shown/hidden

### ISSUE THREAD

**Issue by Arlem** [jwplayer/jwplayer-sdk-android-demo#23]
onControls listener only listens for controls enabled/disabled, correct? Need this to synchronise my custom UI.

**Comment by RikHeijdens** [comment]
We currently do not have a listener for that, but we are currently working on implementing a listener that triggers when the control bar will be shown, or hidden. You can expect it in one of our next releases.

**Comment by hblee** [comment]
onControls() will only tell you if controls are enabled.  What you want is onControlVisibilityChanged(), which fires when the control visibility changes.  This feature will be released in early Feb.

**Comment by Binney** [comment]
+1 This would be really useful, since it already exists for IOS (https://github.com/jwplayer/jwplayer-sdk-ios-demo/issues/3) and we're working on parallel apps for Android and IOS so want to make them as similar as possible.

**Comment by tapankumar** [comment]
When can we get this feature?

**Comment by paulmandal** [comment]
This will be in our next release which should be sometime this week.

**Comment by Binney** [comment]
It's out! https://developer.jwplayer.com/sdk/android/reference/com/longtailvideo/jwplayer/events/listeners/VideoPlayerEvents.OnControlBarVisibilityListener.html

**Comment by Arlem** [comment]
Thank you for your support, I will reopen if I find any issue with it.
