### ISSUE TITLE
Facing duplicate entry problem after adding IMA depndency

### ISSUE THREAD

**Issue by ashishg656** [jwplayer/jwplayer-sdk-android-demo#24]
I am facing some error after adding the IMA dependency.

Error:java.lang.RuntimeException: com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/internal/zzbz.class

Error:com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/internal/zzbz.class

This happened after I added this dependency -
compile 'com.longtailvideo.jwplayer:jwplayer-ima:+'

my app gradle file is  -

`
android{
   .....
    packagingOptions {
        exclude 'jsr305_annotations/Jsr305_annotations.gwt.xml'
    }
}

dependencies {
    compile 'com.android.support:multidex:1.0.1'
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile files('libs/picasso-2.5.2.jar')
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:support-v4:23.1.1'
    compile project(':library')
    compile 'com.google.android.gms:play-services-analytics:10.0.1'
    compile('com.squareup.retrofit:retrofit:2.0.0-beta2') {
        exclude module: 'okhttp'
    }
    compile 'com.squareup.retrofit:converter-gson:2.0.0-beta2'
    compile 'com.squareup.okhttp:okhttp:2.6.0'
    compile 'com.android.support:cardview-v7:23.4.0'
    compile project(':switch_library')
    compile project(':StrmEasyVideoSDK')
    compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
        transitive = true;
    }
    compile 'com.facebook.android:facebook-android-sdk:[4,5)'
    // firebase
    compile 'com.google.firebase:firebase-core:10.0.1'

    compile 'com.android.support:design:23.4.0'
    compile 'io.branch.sdk.android:library:2.+'

    // clevertap
    compile 'com.clevertap.android:clevertap-android-sdk:3.1.1'
    compile 'com.google.android.gms:play-services-gcm:10.0.1'

    // rounded image view https://github.com/vinc3m1/RoundedImageView
    compile 'com.makeramen:roundedimageview:2.2.1'

    // butterknife
    compile 'com.jakewharton:butterknife:8.4.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'

    compile files('libs/volley.jar')
    compile 'com.google.code.gson:gson:2.4'

    compile 'com.google.android.gms:play-services-auth:10.0.1'

    // jw
    compile 'com.longtailvideo.jwplayer:jwplayer-core:+'
    compile 'com.longtailvideo.jwplayer:jwplayer-common:+'
    compile 'com.longtailvideo.jwplayer:jwplayer-ima:+'
}
`

**Comment by GMSyrimis** [comment]
I would suggest looking into the dependencies for all the libraries you are importing to better understand which libraries are importing the problematic classes and choose to exclude the import from one.

**Gradle Docs:**
https://docs.gradle.org/current/userguide/inspecting_dependencies.html
https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html

Closing the thread as it's an issue with dependency management
