### ISSUE TITLE
Chromecast no working even on demo ?

### ISSUE THREAD

**Issue by VizerTV** [jwplayer/jwplayer-sdk-android-demo#26]
My chromecast doesn't play, even the demo project... Everytime i send a video to chromecast, chromecast stops. Is this a compatibility problem?

**Comment by RikHeijdens** [comment]
Do you see any errors being logged to logcat?
Are you building from source or installing the apk that ships with our SDK?

**Comment by VizerTV** [comment]
I've tried from my app, and from the demo...
Every time I select my chromecast device, it reloads and shows nothing.

**Comment by GMSyrimis** [comment]
Hi, if you have not resolved this issue already please contact Support and they can help you troubleshoot this issue. Closing this thread as it's fairly old
