### ISSUE TITLE
Does this player Support WebVTT Subtitle?

### ISSUE THREAD

**Issue by vishalchhodwani1992** [jwplayer/jwplayer-sdk-android-demo#28]
I need to use WebVTT(Subtitle from URL) with m3u8 Streaming audio track. Is it possible to use with JWPlayer?
Does jw-player supports WebVTT with audio Tracks(.m3u8 contains .mp3)?

**Comment by GMSyrimis** [comment]
@vishalchhodwani1992 Yes, you can play HLS stream (.m3u8) that have embedded VTT captions. Closing this thread now
