### ISSUE TITLE
Video time on control bar disappears after changing orientation

### ISSUE THREAD

**Issue by thanhbinh84** [jwplayer/jwplayer-sdk-android-demo#29]
Current version: 2.7.3+19 

Steps to reproduce:  

1. Play video in portrait. Video time displays properly on the control bar.
2. Click the full screen button on the control bar to play video in landscape. 
3. Click the full screen button on the control bar again to play video in portrait. 

![screenshot_2017-05-16-15-29-30-310_com jwplayer opensourcedemo](https://cloud.githubusercontent.com/assets/366768/26097255/2a4a00ba-3a4e-11e7-8f7c-3e7f4e7f032e.png)

**Comment by GMSyrimis** [comment]
@thanhbinh84 This is an old thread so I'll be closing it. Test our latest SDK as this should not be an issue in the 3.x versions of our SDK.
