### ISSUE TITLE
Cannot play links

### ISSUE THREAD

**Issue by kid9591** [jwplayer/jwplayer-sdk-android-demo#30]
JWPlayerView cannot play these two links:

1. https://redirector.googlevideo.com/videoplayback?id=afdb030d76a7f164&itag=18&source=webdrive&requiressl=yes&ttl=transient&mm=30&mn=sn-n4v7kne7&ms=nxu&mv=u&pl=33&sc=yes&ei=4b8bWZovku6pBZnAjfgO&driveid=0B2GhOizgeAmtM0x1clFXME5qelU&mime=video/mp4&lmt=1480238881122584&mt=1494990556&ip=2600:3c01::f03c:91ff:feac:b21&ipbits=0&expire=1495005217&sparams=ip,ipbits,expire,id,itag,source,requiressl,ttl,mm,mn,ms,mv,pl,sc,ei,driveid,mime,lmt&signature=0EDE94AAEAE3A7F3A758FA288013756EC97983B0.92C86ACCC58408C7CE19931811F178577146958E&key=ck2

2. https://r2---sn-8qj-i5oll.googlevideo.com/videoplayback?id=afdb030d76a7f164&itag=18&source=webdrive&requiressl=yes&ttl=transient&pl=24&sc=yes&ei=4b8bWZovku6pBZnAjfgO&driveid=0B2GhOizgeAmtM0x1clFXME5qelU&mime=video/mp4&lmt=1480238881122584&ip=113.190.253.18&ipbits=0&expire=1495005217&sparams=driveid,ei,expire,id,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,requiressl,sc,source,ttl&signature=2AB0F9A19B069FC1378DE9C9405B4D365EBC92C5.15160EDE868CC078B5C3EFC1325E43BC4026BC24&key=cms1&cms_redirect=yes&mm=31&mn=sn-8qj-i5oll&ms=au&mt=1494990743&mv=m

A message show up: "No playable resources". However, when I paste these links to Web browser they can play directly. Moreover, these links can work with JCPlayer (https://github.com/jeancsanchez/JcPlayer).

Please provide explanation or fix if you consider this as a bug.

**Comment by RikHeijdens** [comment]
There is no media extension (e.g. `http://server.com/video.mp4`) in these URLs, which is something the JWPlayerView requires.
