### ISSUE TITLE
problem with new version when generating signed apk

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [jwplayer/jwplayer-sdk-android-demo#31]
Hi,
we upgrade our jw from
2.6.3+14 to 2.7.3+19
but we got an error when signing apk in android studio.
android studio version: 2.3.2

error :
Warning:Exception while processing task java.io.IOException: java.lang.IllegalArgumentException: Overflow of unsigned short value [66350]
Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForAppRelease'.
> Job failed, see logs for details

**Comment by jemshit** [comment]
looks like you have error in your proguard file, not related to this lib
