### ISSUE TITLE
Not possible remove mute when it auto play

### ISSUE THREAD

**Issue by naguchennai** [jwplayer/jwplayer-sdk-android-demo#32]
PlayerConfig playerConfig = new PlayerConfig.Builder()
                .file(VIDEO_URL)
                .autostart(true)
                .mute(false)
                .build();

mute not disabled if we enable autostart

**Comment by GMSyrimis** [comment]
This is a known issue. As a workaround call mPlayerView.play(true); after setup.

**Comment by naguchennai** [comment]
`       playerView = (JWPlayerView) findViewById(R.id.playerView);

        PlayerConfig playerConfig = new PlayerConfig.Builder()
                .file(VIDEO_URL)
                .autostart(true)
                .build();
        playerView.play(true);
        playerView = new JWPlayerView(VideoView_Activity.this, playerConfig);
        ViewGroup jwPlayerViewContainer = (ViewGroup) findViewById(R.id.framlayout);
        jwPlayerViewContainer.addView(playerView);`
Still Audio is muted
