### ISSUE TITLE
JW player video not plays in fullscreen

### ISSUE THREAD

**Issue by cyberformed** [jwplayer/jwplayer-sdk-android-demo#33]
I have integrated JW Player into android using android SDK. But the issue persists when the user turns to landscape mode / clicks on full screen, then the video moves to Landscape mode with half of the screen and starts from the beginning which can cost to the user to use double bandwidth and internet.

Does any guy have solution to it, I have customized  a lot, but nothing seems to work. Need help in this regard ASAP.

```
    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        if (newConfig.orientation == Configuration.ORIENTATION_PORTRAIT) {
            if (mPlayerView.getFullscreen()) {
                mPlayerView.setFullscreen(false, true);
            }
        } else if (newConfig.orientation == Configuration.ORIENTATION_LANDSCAPE) {
            if (!mPlayerView.getFullscreen()) {
                mPlayerView.setFullscreen(true, true);
            }
        }
    }
```

**Comment by GMSyrimis** [comment]
Hi, sounds like you're not using

```
<activity
    ...
    android:configChanges="keyboard|keyboardHidden|orientation|screenSize" >
```

https://developer.jwplayer.com/sdk/android/docs/developer-guide/getting-started/library-project-setup/

**Comment by cyberformed** [comment]
Team,

Thanks for your quick response. Now it's working fine.
