### ISSUE TITLE
[help] Google drive video streaming not working

### ISSUE THREAD

**Issue by xellDart** [jwplayer/jwplayer-sdk-android-demo#34]
I try to put my link from gdrive like this:
https://doc-0c-80-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/qhphr04frof78029bl2dlis9ripr2ug9/1500141600000/04236477348342191841/*/0B3-d1qBwE5oRdVp2NWlyRWx3NDg?e=download

in
// Load a media source
		PlaylistItem pi = new PlaylistItem.Builder()
				.file("https://doc-0s-80-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/ce557of7u7btc4t2lr6dljcb0lcq4qmk/1500141600000/04236477348342191841/*/0B3-d1qBwE5oRWW1lSUVOTk5FWGs?e=download")
				.title("BipBop")
				.description("A video player testing video.")
				.build();
		mPlayerView.load(pi);

But this not worked, and with html frmae is working

**Comment by GMSyrimis** [comment]
@xellDart I don't think that will work. The videos on Google drive are not usually accessible like that. For starters I'd confirm you are actually getting an mp4 back if you `curl` that URL. If the content type checks out, then try setting up a `MediaSource` object and assigning that to a `PlaylistItem`.
