### ISSUE TITLE
Cookie

### ISSUE THREAD

**Issue by mauriciopostal** [jwplayer/jwplayer-sdk-android-demo#35]
How can I set cookies for JWPlayer request?

Like iOS:
https://github.com/jwplayer/jwplayer-sdk-ios-demo/issues/21

**Comment by GMSyrimis** [comment]
@mauriciopostal https://developer.jwplayer.com/sdk/android/reference/com/longtailvideo/jwplayer/media/playlists/PlaylistItem.html#setHttpHeaders-java.util.Map-
