### ISSUE TITLE
DRM .m308 Sample

### ISSUE THREAD

**Issue by laithnurie** [jwplayer/jwplayer-sdk-android-demo#36]
Can you include a DRM example in the sample app?

**Comment by user2radhoosh** [comment]
I need the example too.

**Comment by GMSyrimis** [comment]
Unfortunately, keeping a DRM server running indefinitely is not optimal. If you are working with DRM content I recommend you get a sample stream from your DRM provider. JW Player now offers DRM via JW Stream:
https://developer.jwplayer.com/jwplayer/docs/enable-drm-with-jw-stream
Closing this thread as it's fairly old
