### ISSUE TITLE
Full screen is not working properly in fragment

### ISSUE THREAD

**Issue by sountharya** [jwplayer/jwplayer-sdk-android-demo#39]
Hi 
 I am trying to use jwplayer in my fragment class. Its working good in portrait mode. 
When I click fullscreen button it is not working.
It remains in portrait mode only.
I gave permission to both landscape and portrait mode.
And the phone setting is also set to autorotate.
But the fullscreen is not working in fragment class.
I gave my code on below for your reference.
Please suggest any solution.

Thank you

package com.sysnx.lecture.capture.Fragment;

import android.content.Context;
import android.content.res.Configuration;
import android.os.Bundle;
import android.os.PowerManager;
import android.support.design.widget.CoordinatorLayout;
import android.support.v4.app.Fragment;
import android.support.v7.app.ActionBar;
import android.support.v7.app.ActionBarActivity;
import android.support.v7.app.AppCompatActivity;

import android.util.DisplayMetrics;
import android.util.Log;
import android.view.KeyEvent;
import android.view.LayoutInflater;
import android.view.MotionEvent;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.RelativeLayout;

import com.longtailvideo.jwplayer.JWPlayerView;
import com.longtailvideo.jwplayer.configuration.PlayerConfig;
import com.longtailvideo.jwplayer.core.PlayerState;
import com.longtailvideo.jwplayer.events.listeners.VideoPlayerEvents;
import com.longtailvideo.jwplayer.media.audio.AudioTrack;
import com.sysnx.lecture.capture.Activity.MainActivity;
import com.sysnx.lecture.capture.Pojo.Pojo;
import com.sysnx.lecture.capture.R;
import com.sysnx.lecture.capture.Utils.MovableFrameLayout;

import java.util.ArrayList;
import java.util.List;

import static com.sysnx.lecture.capture.Utils.Constants.FILEPATH;

/**
 * Created by sysnx on 5/9/17.
 */

public class PlayerFragment extends BaseFragment implements VideoPlayerEvents.OnFullscreenListener,
        VideoPlayerEvents.OnPlayListener, VideoPlayerEvents.OnPauseListener, VideoPlayerEvents.OnCompleteListener,
        VideoPlayerEvents.OnSeekedListener, VideoPlayerEvents.OnTimeListener, VideoPlayerEvents.OnAudioTracksListener {

    private static final double SCALING_FACTOR = 1.75;
    private JWPlayerView mPlayerView;
    private MovableFrameLayout mPlayerContainer;
    private CoordinatorLayout mCoordinatorLayout;
    private RelativeLayout mContentContainer;
    private ViewGroup.LayoutParams mInitialLayoutParams;
    Boolean isRotated =true;
    protected PowerManager.WakeLock mWakeLock;
    private PlayerState mPlayerState;
    String url;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {

        View v = inflater.inflate(R.layout.activity_main, container, false);

        final PowerManager pm = (PowerManager) getActivity().getSystemService(Context.POWER_SERVICE);
        this.mWakeLock = pm.newWakeLock(PowerManager.SCREEN_DIM_WAKE_LOCK, "My Tag");
        this.mWakeLock.acquire();
        url = getSharedPreferenceValue(FILEPATH);
        url = url.replaceAll(" ", "%20");
        // Get a reference to the CoordinatorLayout
        mCoordinatorLayout = (CoordinatorLayout) v.findViewById(R.id.coordinator_layout);
        mContentContainer = (RelativeLayout) v.findViewById(R.id.main_container);
        // Get a reference to the FrameLayout that we will use to contain the player in.
        mPlayerContainer = (MovableFrameLayout) v.findViewById(R.id.player_container);
    

        mPlayerView = new JWPlayerView(getActivity(), new PlayerConfig.Builder()
                .file(url)
                .build());
        mPlayerView.addOnFullscreenListener(this);
        mPlayerView.addOnPlayListener(this);
        mPlayerView.addOnPauseListener(this);
        mPlayerView.addOnCompleteListener(this);

        // Add the View to the View Hierarchy.
        mPlayerContainer.addView(mPlayerView);
        setInitialLayoutParams();
        return v;
    }

    @Override
    public void onSeeked() {

    }

    @Override
    public void onTime(long l, long l1) {

    }

    @Override
    public void onAudioTracks(List<AudioTrack> list) {

    }

    /**
     * Sets the initial layout parameters for the {@link JWPlayerView}.
     */
    private void setInitialLayoutParams() {
        DisplayMetrics displayMetrics = getResources().getDisplayMetrics();
        if (getResources().getConfiguration().orientation == Configuration.ORIENTATION_PORTRAIT) {
            mPlayerContainer.setLayoutParams(new RelativeLayout.LayoutParams(
                    ViewGroup.LayoutParams.MATCH_PARENT, (displayMetrics.widthPixels / 16) * 9)); // 16:9
        } else {
            // We need to use height to calculate a 16:9 ratio since we're in landscape mode.
            mPlayerContainer.setLayoutParams(new RelativeLayout.LayoutParams(
                    ViewGroup.LayoutParams.MATCH_PARENT, (displayMetrics.heightPixels / 16) * 9)); // 16:9
            // Toggle fullscreen, since we're in landscape mode.
            mPlayerView.setFullscreen(true, true);
        }
    }

    /**
     * Positions the movable player to the right bottom corner.
     *
     * @param layoutParams
     * @return
     */
    private RelativeLayout.LayoutParams getInitialMovablePlayerLayoutParams(RelativeLayout.LayoutParams layoutParams) {
        layoutParams.addRule(RelativeLayout.ALIGN_PARENT_BOTTOM);
        layoutParams.addRule(RelativeLayout.ALIGN_PARENT_RIGHT);
        DisplayMetrics displayMetrics = getResources().getDisplayMetrics();
        layoutParams.setMargins(0, 0, Math.round(displayMetrics.density * 16), Math.round(displayMetrics.density * 16));
        return layoutParams;
    }

    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        if (newConfig.orientation == Configuration.ORIENTATION_PORTRAIT) {
            if (mPlayerView.getFullscreen()) {
                mPlayerView.setFullscreen(false, true);
            }
        } else if (newConfig.orientation == Configuration.ORIENTATION_LANDSCAPE) {
            if (!mPlayerView.getFullscreen()) {
                mPlayerView.setFullscreen(true, true);
            }
        }
    }

    @Override
    public void onResume() {
        // Let JW Player know that the app has returned from the background
        // mPlayerView.onResume();
        super.onResume();
    }

    @Override
    public void onPause() {
        // Let JW Player know that the app is going to the background
        //  mPlayerView.onPause();
        super.onPause();
    }

    @Override
    public void onDestroy() {
        // Log.i(UIH.TAG_SCR, "Is Rotated : " + isRotated);
        if (!isRotated) {
            mPlayerView.stop();
        } else {
            isRotated = false;
        }
        super.onDestroy();
    }

    /**
     * Handles JW Player going to and returning from fullscreen by hiding the ActionBar
     *
     * @param fullscreen true if the player is fullscreen
     */
    @Override
    public void onFullscreen(boolean fullscreen) {

        if (fullscreen) {
            onResume();
                /*
                 * Because we are using a coordinator layout, which has setFitsSystemWindows set
                 * to 'true' by default, we need to disable this when the JW Player View goes into
                 * fullscreen. If we would not do this, the activity will not properly hide the
                 * system UI.
                 */

            mCoordinatorLayout.setFitsSystemWindows(false);
            
        } else {
            onResume();
            mPlayerView.setFullscreen(getResources().getConfiguration().orientation
                    == Configuration.ORIENTATION_LANDSCAPE, true);
            mCoordinatorLayout.setFitsSystemWindows(true);

        }

    }

   /* @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        // If we are in fullscreen mode, exit fullscreen mode when the user uses the back button.
        if (keyCode == KeyEvent.KEYCODE_BACK) {
            if (mPlayerView.getFullscreen()) {
                mPlayerView.setFullscreen(false, true);
                return true;
            }
        }
        return super.onKeyDown(keyCode, event);
    }*/

    @Override
    public void onPlay(PlayerState playerState) {
        mPlayerState = playerState;
    }

    @Override
    public void onComplete() {
        mPlayerState = PlayerState.IDLE;
    }

    @Override
    public void onPause(PlayerState playerState) {
        mPlayerState = playerState;
    }
}

**Comment by darrelRayen** [comment]
Hi.. is there any updates on this ?

**Comment by GMSyrimis** [comment]
@darrelRayen Is the expected behavior simply to have a Fragment go fullscreen?

If that's the case, have a look at the `JWPlayerSupportFragment` class

Closing thread as it is stale
