### ISSUE TITLE
Video is reloading when open in fullscreen.

### ISSUE THREAD

**Issue by sountharya** [jwplayer/jwplayer-sdk-android-demo#40]
Hi 

When I click the full screen button the video is not resuming from the part which I have played in portrait mode.
It is playing from the beginning.Same thing occurs when going back from full screen to portrait.
I want to resume the video when I press full screen button.
Please tell me how to do it?

Thank You.

**Comment by GMSyrimis** [comment]
@sountharya Sounds like you were not setting up the `configChanges`element for the Activity in your manifest:
https://developer.jwplayer.com/sdk/android/docs/developer-guide/getting-started/configure-the-manifest/

Closing this thread as stale
