### ISSUE TITLE
custom layout for jwplayer

### ISSUE THREAD

**Issue by sn32247** [jwplayer/jwplayer-sdk-android-demo#46]
i want design custom music player with jwplayer that have custom button for next,prev,pause,play and ...
do jwplayer support this ?

**Comment by GMSyrimis** [comment]
@sn32247 Yes, we support a native custom UI and background audio playback.
Have a look at this repo for ideas:
https://github.com/jwplayer/jwplayer-android-best-practice-apps

Closing this thread
