### ISSUE TITLE
Getting error 'Invalid HTTP response code: 404: Not Found' on lots of Media URLs. But the same Media URLs are working fine on Live App

### ISSUE THREAD

**Issue by deeps2HOG** [jwplayer/jwplayer-sdk-android-demo#53]
Two days ago, All of a sudden I was getting error: `More than one file was found with OS independent path [...]`" while building APK. On doing more research I find out that it's related to ExoPlayer. 
Here is the corresponding link for ExoPlayer issue: https://github.com/google/ExoPlayer/issues/3911.
and 
stackoverflow post: https://stackoverflow.com/questions/49423572/android-unable-to-build-apk-more-than-one-file-was-found-with-os-independent-p/49424933#49424933

I followed the workaround mentioned in above link and build was successful . Although build was successful, I noticed that I am not able to play most of the media URLs. Same media URLs are working fine on live App. I am using JWPlayer SDK for media streaming. Everytime I open the `VideoActivity`, I get `onError() `callback with error message:  `Invalid HTTP response code: 404: Not Found`. 

According to JWPlayer changelog: 
https://developer.jwplayer.com/sdk/android/docs/developer-guide/about/release-notes/ 
SDK was updated on Mar21, 2018 (updated Google IMA library to version 3.8.2 but in the latest Exoplayer release (2.7.0) it still uses version 3.7.4 of the IMA SDK.) and since that day I am also getting the error. As JWPlayer for Android is built on top of ExoPlayer I think this ExoPlayer-IMA issue gets inherited in JWPlayer while updating the SDK to Version 2.8.1 (Build 43 - Mar 21, 2018)

In the SDK setup instructions https://developer.jwplayer.com/sdk/android/docs/developer-guide/getting-started/library-project-setup/ it is recommended to use + while including dependencies. If I try to build by specifying a lower version (2.8.0) in gradle. I get an error while syncing: `Failed to resolve: com.longtailvideo.jwplayer:jwplayer-core:2.8.0`.

So, How to resolve this? I have an upcoming release next week

**Comment by GMSyrimis** [comment]
@deeps2HOG Please provide the following:

**Issue Summary:**

**JWP SDK Ver #:**

**OS Version:** 

**Device make & model:**

**IDE:**

**Video or Screenshots:** 

**Demo App source code experiencing the issue:** 

**Steps to reproduce:**
1. First step
2. Second step
3. Third step (BUG)

**Expected Behavior:**

**Actual Behavior:**

**Log / Stack Trace of exceptions, errors, etc:**
