### ISSUE TITLE
JWPlayer with fast-forward and rewind buttons in android

### ISSUE THREAD

**Issue by sn32247** [jwplayer/jwplayer-sdk-android-demo#58]
I am using jwplayer in android project.Now the requirement states that the player should have "Fast-FORWARD" and "REWIND" button .

I have looked at the documentation but did not find anything in android sdk.

**Comment by GMSyrimis** [comment]
@sn32247 For the fast forward component, have a look at our API:
https://developer.jwplayer.com/sdk/android/reference/com/longtailvideo/jwplayer/configuration/PlaybackRateConfig.html
For rewind, we don't have a specific API for this. You could simply call `mPlayer.seek(mPlayer.getPosition()-5)` and build it such a way that long clicks call it repeatedly.

Closing the ticket as stale
