### ISSUE TITLE
Subtitles are shown at screen center instead of at screen bottom

### ISSUE THREAD

**Issue by ChemaIturbe** [jwplayer/jwplayer-sdk-android-demo#63]
Device: Samsung Galaxy S8
Android Version: 8.0.0
Olympic Channel App versión: 1.18.0
Android SDK 2.9.0
Language: English
StreamingUrl: https://vod.olympicchannel.com/NBCR_Production_-_OCS/231/1016/GEPH-ONTHERECS02E012C-_E17101101_master.m3u8
FilePath: NBCR_Production_-_OCS/231/1016/GEPH-ONTHERECS02E012C-_E17101101_master.m3u8

Steps:
1.- Open OC app
2.- Tap on "Explora" icon at button right menu
3.- Tap on Originals
4.- Scroll down until "Our Originals" section
5.- Tap on "THE OLYMPICS ON THE RECORD" serie
6.- Tap on "Argentina Score Football Perfection in Athens" episode
7.- Observe

Subtitles are shown at screen center instead of at screen bottom

**Comment by GMSyrimis** [comment]
This is an old thread. If you are a customer, please submit a support ticket so our team can get back to you promptly in the future.
