### ISSUE TITLE
Get URL by media video

### ISSUE THREAD

**Issue by NDNELSON** [jwplayer/jwplayer-sdk-android-demo#64]
Hello I realized that from videos that we have in your platform we access by JavaScript file in web. But what happen in Android api. Is there a way to get url from video’s media id ?

**Comment by hyunjkim** [comment]
You will have to make an HTTP request to our Delivery API, https://developer.jwplayer.com/jw-platform/docs/delivery-api-reference/ then parse the response, I've create pojos for them, and then I've passed it to the player. 

I've tried doing that with Adschedule ID, https://developer.jwplayer.com/jw-platform/docs/delivery-api-reference/

**Comment by GMSyrimis** [comment]
Closing this thread as stale
