### ISSUE TITLE
incompatible types: List<com.google.android.exoplayer.metadata.id3.Id3Frame> cannot be converted to List<com.google.android.exoplayer2.metadata.id3.Id3Frame>

### ISSUE THREAD

**Issue by pacifire** [jwplayer/jwplayer-sdk-android-demo#68]
I am trying to run the Sample Github project since last 2 days.

But getting this error: 
incompatible types: List<com.google.android.exoplayer.metadata.id3.Id3Frame> cannot be converted to List<com.google.android.exoplayer2.metadata.id3.Id3Frame>

The line where I am getting this error is:

> List<com.google.android.exoplayer2.metadata.id3.Id3Frame> id3 = meta.getId3Metadata();

There are lots of errors, while using this DEMO.

I request @jwplayer-robot @jwplayermurphy: JW Player Team, to rewrite the documentation & rewrite the DEMO.
The demo is too OLD to use.

**Comment by hyunjkim** [comment]
@pacifire, I don't think that is part of the SDK v3.x, if you have **3+** in your dependency, you're pulling the latest, there were some modifications and additions, check it out here https://developer.jwplayer.com/sdk/android/docs/developer-guide/migration/v3/. 

I have v2.x (Branch: masterV2) and v3.x (Branch: masterV3, under different branches: https://github.com/hyunjkim/jwplayer-sdk-android-demo,

**Comment by vindhyapratap** [comment]
I am getting this error while using sdk for ima ads 

implementation 'com.longtailvideo.jwplayer:jwplayer-core:3.7.0'
implementation 'com.longtailvideo.jwplayer:jwplayer-common:3.7.0'
implementation 'com.longtailvideo.jwplayer:jwplayer-ima:3.7.0'


 **error: incompatible types: AdSource cannot be converted to List<AdBreak>
        ImaAdvertising imaAdvertising = new ImaAdvertising(AdSource.IMA, adSchedule);**

Its not getting constructor for passing AdSource.IMA and document is not updated according to this.

**Comment by GMSyrimis** [comment]
@vindhyapratap The `ImaAdvertising` constructor does not take an `AdSource` as a parameter:
https://developer.jwplayer.com/sdk/android/reference/com/longtailvideo/jwplayer/media/ads/ImaAdvertising.html#constructor.summary

@pacifire Have you tried the latest demo? 

Closing this thread as it's currently stale
