### ISSUE TITLE
Cannot set User-Agent on SDK 3.x

### ISSUE THREAD

**Issue by chanai-m** [jwplayer/jwplayer-sdk-android-demo#70]
JWPlayer always sent user-agent header "ExoPlayerDemo/1.0 (Linux;Android x) ExoPlayerLib/x.x.x" to server.

```
Map<String, String> httpHeaders = new HashMap<>();
httpHeaders.put("Custom-Agent", "Test-Custom-Agent");  <---- This one will add another headers and work fine
httpHeaders.put("User-Agent", "Test-Agent"); <---- This one will always "ExoPlayerDemo/1.0 (Linux;Android x) ExoPlayerLib/x.x.x" 

```

I also tried to use updateHttpHeaders before setup and after setup
```
mPlayerView.updateHttpHeaders(httpHeaders);
mPlayerView.setup(config);
mPlayerView.updateHttpHeaders(httpHeaders);
```

And tried to modify header onBeforePlay event
```
@Override
public void onBeforePlay(BeforePlayEvent beforePlayEvent) {
mPlayer.updateHttpHeaders(httpHeaders);
}
```

**Comment by hyunjkim** [comment]
This was shared from our engineering team, @paulmandal , does this work for you?  

`WebView webView = null;
for (int i = 0 ; i < mPlayerView.getChildCount() ; i++) {
    View v = mPlayerView.getChildAt(i);
    if (v instanceof WebView) {
        webView = (WebView)v;
        break;
    }
}
webView.getSettings().setUserAgentString("Android");`

**Comment by karimMourra** [comment]
@chanai-m why do you need to change the user agent ? Could you please explain your use case; we may be able to find an alternative that solves your problem

**Comment by hdwilber** [comment]
@karimMourra My media service provider requires it for analytics. I think that is a basic configuration that should be available.
I am struggling finding a way to do so. Looks like the request to the server is sent during instantiation without the new headers.

Data sources for ExoPlayer allow us to easily setup the user agent for requests. For example: https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/DefaultDataSourceFactory.html#DefaultDataSourceFactory-android.content.Context-java.lang.String-

**Comment by GMSyrimis** [comment]
If you haven't resolved the issue yet, please contact support. They can help troubleshoot the issue. Closing this thread as it's fairly old
