### ISSUE TITLE
Chromecast Button Color

### ISSUE THREAD

**Issue by LSanfordCarbonTV** [jwplayer/jwplayer-sdk-android-demo#77]
Hi,

When I run the demo app, the Chromecast button is easily visible using the JWPlayerView example.

But when I switch to the JWPlayerFragment example, the button is very hard to see.

Is there a way to fix this? I'm using JWPlayerFragment in my app, and you can hardly see the Chromecast button due to its color.

![jwplayerfragment-chromecastbutton](https://user-images.githubusercontent.com/38786195/53910607-da292380-4019-11e9-90aa-718144b77b29.jpg)

![jwplayerview-chromcastbutton](https://user-images.githubusercontent.com/38786195/53910605-d72e3300-4019-11e9-824f-375c5b65f9a0.jpg)

**Comment by NiravPotenza** [comment]
Hello 
i had also download the sample code but there is no Chromecast button is easily visible can u please send me your sample code..?

**Comment by LSanfordCarbonTV** [comment]
I'm not sure what has changed, but this appears to be fixed in the latest version of the demo. The cast button is easily visible in both the View and Fragment examples.
