### ISSUE TITLE
How to change mediapalyer 

### ISSUE THREAD

**Issue by nimamyscreen** [jwplayer/jwplayer-sdk-android-demo#8]
I see a layout in this project (custom_media_route_controller_controls_dialog) but I dont know how to use it in program. I need to change the mediaplayer design based on my app.

**Comment by RikHeijdens** [comment]
The `custom_media_route_controller_controls_dialog.xml` layout file is used to for the MediaRouteController dialog, it is the dialog that you see when you're casting to a Chromecast and you tap the "Casting" button in the action bar.

Changing the design of the player in the JWPlayerView is done by CSS files. You can create your own custom css file and set it on the JWPlayerView using the `setSkin` method. Please check our [developer guide](https://developer.jwplayer.com/jw-player/docs/developer-guide/customization/css-skinning/skins_reference/) for more information about skinning the player.
