### ISSUE TITLE
Need to play video and audio from local (sd-card)

### ISSUE THREAD

**Issue by macroday** [jwplayer/jwplayer-sdk-android-demo#80]
Hi Team,

I need to do play offline video and audio files from sd-card or some other. Is there any api support for this? 

Thanks in advance.

**Comment by karimMourra** [comment]
@macroday it should work out of the box. You have to reference the file path in SD card.

**Comment by macroday** [comment]
I tried both external and internal file path. But it couldn't work. Here is my sample code.

```
 PlayerConfig playerConfig = new PlayerConfig.Builder()
                .file(new File(Environment.getExternalStorageDirectory().getAbsolutePath()+"/sample.mp4").getAbsolutePath())
                .image(mModel.getImage())
                .autostart(playVideo)
                .skinName("sample")
                .build();
        mVideoView.setup(playerConfig);
```

Please provide any sample code to make it right.

**Comment by macroday** [comment]
Any Insights team?

**Comment by GMSyrimis** [comment]
If you haven't resolved the issue yet, please contact support. They can help troubleshoot the issue. Closing this thread as it's fairly old
