### ISSUE TITLE
inflating class com.longtailvideo.jwplayer.JWPlayerView

### ISSUE THREAD

**Issue by NiravPotenza** [jwplayer/jwplayer-sdk-android-demo#81]
your demo is working fine when i try to implement in my project it's throw exception like 
`Binary XML file line #13: Error inflating class com.longtailvideo.jwplayer.JWPlayerView` 

` Caused by: java.lang.ClassNotFoundException: Didn't find class "com.jwplayer.opensourcedemo.CastOptionsProvider" on path: DexPathList[[zip file "/data/app/com.islandtouch.app-TVZSCn_seUECQOTokPAffA==/base.apk"],nativeLibraryDirectories=[/data/app/com.islandtouch.app-TVZSCn_seUECQOTokPAffA==/lib/arm64, /system/lib64]]`

//My Gradle
 ```
  //jwplayer
    implementation 'com.longtailvideo.jwplayer:jwplayer-core:3.5.0'
    implementation 'com.longtailvideo.jwplayer:jwplayer-common:3.5.0'

    // Only required if using Chromecast
    implementation 'com.longtailvideo.jwplayer:jwplayer-chromecast:3.5.0'

    // Only required if using FreeWheel
    implementation 'com.longtailvideo.jwplayer:jwplayer-freewheel:3.5.0'

    // Only required if using IMA features
    implementation 'com.longtailvideo.jwplayer:jwplayer-ima:3.5.0'

```
Please provide me Solution

**Comment by NiravPotenza** [comment]
hello jwplayer-sdk-android-demo
is there any fix or solution for my Question ..?

**Comment by vindhyapratap** [comment]
@NiravPotenza Have got any solution for this

**Comment by codal-mpawar** [comment]
@NiravPotenza Have you any solution for this?

**Comment by vibhorji** [comment]
Create new Demo app and write xml code manually.

**Comment by MannForApi** [comment]
facing same issue, @vibhorji  is that fixed for you. Please let me know what was the fix

**Comment by jigneshpandav** [comment]
+1 Any update on this?

**Comment by mwaked** [comment]
+1 Any Update??

**Comment by yejong2013** [comment]
facing same issue

**Comment by WahajMubeen341** [comment]
Hey everyone! any fix for this error?? 
I am facing the exact same issue.

**Comment by WahajMubeen341** [comment]
> Hey everyone! any fix for this error??
> I am facing the exact same issue.

Fixed by one of the answers above:
update jwplayer dependency version to :
*
implementation 'com.longtailvideo.jwplayer:jwplayer-core:3.15.1'
implementation 'com.longtailvideo.jwplayer:jwplayer-common:3.15.1'
*

**Comment by GMSyrimis** [comment]
If you haven't resolved the issue yet, please contact support. They can help troubleshoot the issue. Closing this thread as it's fairly old. 

As mentioned by another community developer, the solution is to update to the latest version of the SDK and make sure you check the XML layout file. Sometimes an `Invalidate Cache and Restart` is necessary to get Android Studio to recognize the changes.
