### ISSUE TITLE
Android Issue react-native run-time error

### ISSUE THREAD

**Issue by codal-mpawar** [jwplayer/jwplayer-sdk-android-demo#88]
when I run the example app then that error was displayed what I do? Please help me 

Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> Could not find com.longtailvideo.jwplayer:jwplayer-core:3.5.0.
  Searched in the following locations:
      file:/Users/codal/Library/Android/sdk/extras/m2repository/com/longtailvideo/jwplayer/jwplayer-core/3.5.0/jwplayer-core-3.5.0.pom
      file:/Users/codal/Library/Android/sdk/extras/m2repository/com/longtailvideo/jwplayer/jwplayer-core/3.5.0/jwplayer-core-3.5.0.jar
      file:/Users/codal/Library/Android/sdk/extras/google/m2repository/com/longtailvideo/jwplayer/jwplayer-core/3.5.0/jwplayer-core-3.5.0.pom
      file:/Users/codal/Library/Android/sdk/extras/google/m2repository/com/longtailvideo/jwplayer/jwplayer-core/3.5.0/jwplayer-core-3.5.0.jar
      file:/Users/codal/Library/Android/sdk/extras/android/m2repository/com/longtailvideo/jwplayer/jwplayer-core/3.5.0/jwplayer-core-3.5.0.pom
      file:/Users/codal/Library/Android/sdk/extras/android/m2repository/com/longtailvideo/jwplayer/jwplayer-core/3.5.0/jwplayer-core-3.5.0.jar
      https://dl.google.com/dl/android/maven2/com/longtailvideo/jwplayer/jwplayer-core/3.5.0/jwplayer-core-3.5.0.pom
      https://dl.google.com/dl/android/maven2/com/longtailvideo/jwplayer/jwplayer-core/3.5.0/jwplayer-core-3.5.0.jar
      file:/Users/codal/.m2/repository/com/longtailvideo/jwplayer/jwplayer-core/3.5.0/jwplayer-core-3.5.0.pom
      file:/Users/codal/.m2/repository/com/longtailvideo/jwplayer/jwplayer-core/3.5.0/jwplayer-core-3.5.0.jar
      https://jcenter.bintray.com/com/longtailvideo/jwplayer/jwplayer-core/3.5.0/jwplayer-core-3.5.0.pom
      https://jcenter.bintray.com/com/longtailvideo/jwplayer/jwplayer-core/3.5.0/jwplayer-core-3.5.0.jar
      file:/Users/codal/Downloads/react-native-jw-media-player-master/Example/node_modules/react-native/android/com/longtailvideo/jwplayer/jwplayer-core/3.5.0/jwplayer-core-3.5.0.pom
      file:/Users/codal/Downloads/react-native-jw-media-player-master/Example/node_modules/react-native/android/com/longtailvideo/jwplayer/jwplayer-core/3.5.0/jwplayer-core-3.5.0.jar
  Required by:
      project :app > project :react-native-jwplayer
> Could not find com.longtailvideo.jwplayer:jwplayer-common:3.5.0.
  Searched in the following locations:
      file:/Users/codal/Library/Android/sdk/extras/m2repository/com/longtailvideo/jwplayer/jwplayer-common/3.5.0/jwplayer-common-3.5.0.pom
      file:/Users/codal/Library/Android/sdk/extras/m2repository/com/longtailvideo/jwplayer/jwplayer-common/3.5.0/jwplayer-common-3.5.0.jar
      file:/Users/codal/Library/Android/sdk/extras/google/m2repository/com/longtailvideo/jwplayer/jwplayer-common/3.5.0/jwplayer-common-3.5.0.pom
      file:/Users/codal/Library/Android/sdk/extras/google/m2repository/com/longtailvideo/jwplayer/jwplayer-common/3.5.0/jwplayer-common-3.5.0.jar
      file:/Users/codal/Library/Android/sdk/extras/android/m2repository/com/longtailvideo/jwplayer/jwplayer-common/3.5.0/jwplayer-common-3.5.0.pom
      file:/Users/codal/Library/Android/sdk/extras/android/m2repository/com/longtailvideo/jwplayer/jwplayer-common/3.5.0/jwplayer-common-3.5.0.jar
      https://dl.google.com/dl/android/maven2/com/longtailvideo/jwplayer/jwplayer-common/3.5.0/jwplayer-common-3.5.0.pom
      https://dl.google.com/dl/android/maven2/com/longtailvideo/jwplayer/jwplayer-common/3.5.0/jwplayer-common-3.5.0.jar
      file:/Users/codal/.m2/repository/com/longtailvideo/jwplayer/jwplayer-common/3.5.0/jwplayer-common-3.5.0.pom
      file:/Users/codal/.m2/repository/com/longtailvideo/jwplayer/jwplayer-common/3.5.0/jwplayer-common-3.5.0.jar
      https://jcenter.bintray.com/com/longtailvideo/jwplayer/jwplayer-common/3.5.0/jwplayer-common-3.5.0.pom
      https://jcenter.bintray.com/com/longtailvideo/jwplayer/jwplayer-common/3.5.0/jwplayer-common-3.5.0.jar
      file:/Users/codal/Downloads/react-native-jw-media-player-master/Example/node_modules/react-native/android/com/longtailvideo/jwplayer/jwplayer-common/3.5.0/jwplayer-common-3.5.0.pom
      file:/Users/codal/Downloads/react-native-jw-media-player-master/Example/node_modules/react-native/android/com/longtailvideo/jwplayer/jwplayer-common/3.5.0/jwplayer-common-3.5.0.jar
  Required by:
      project :app > project :react-native-jwplayer

**Comment by GMSyrimis** [comment]
Unfortunately, we do not support React Native 😞 . Closing this thread as it's fairly old
