### ISSUE TITLE
Duplicate captions display when using both side-loaded and embedded in-stream 608 captions

### ISSUE THREAD

**Issue by jjhampton** [jwplayer/jwplayer-sdk-android-demo#93]
I'm seeing duplicate captions displaying when a playlist item video file is an HLS stream w/ embedded CEA-608 captions, but the playlist item also has sidecar captions added:

This occurs in my app, and is also reproducible in the JWPlayer SDK Android Demo:

In JWPlayerViewExample.java, onCreate method:

```
List<Caption> captionTracks = new ArrayList<>();
Caption captionEn = new Caption.Builder()
  .file("https://sidecar-captions-file.srt") . << sidecar caption file
  .label("English")
  .isdefault(true)
  .build();
captionTracks.add(captionEn);

// Same code below as in demo, but with a video that has embedded captions
// Load a media source
PlaylistItem pi = new PlaylistItem.Builder()
  .file("https://video-with-embedded-captions.m3u8") . << embedded video URL here
  .title("BipBop")
  .description("A video player testing video.")
  .tracks(captionTracks)
  .build();
```

I see that this bug was recently fixed for the iOS SDK in v3.6.3: https://www.jwplayer.com/release-notes/ios-sdk/?id=18588336: "Fixed an issue where 608 captions can not be disabled in a playlist item containing side-loaded captions", possibly the same as reported here: https://github.com/jwplayer/jwplayer-sdk-ios-demo/issues/60 .

Will this be fixed for the Android SDK, or will there be a way to manually turn off the embedded captions, if sidecar captions are used?

**Comment by askolodny** [comment]
Hi @jjhampton this has been fixed in our Android 3.10.0 release. Thank you for reporting!
