### ISSUE TITLE
jw player timeout

### ISSUE THREAD

**Issue by santosh-vishwakarma** [jwplayer/jwplayer-sdk-android-demo#97]
JW player is not loading mp4 when publishing the app under API version 28.
It works fine in API 26.
JW Player is imported in ionic 2.
This problem seems to have occurred recently after an android update.
Please guide.

![WhatsApp Image 2020-01-23 at 9 44 15 AM](https://user-images.githubusercontent.com/22681983/72958935-b7893000-3dce-11ea-9d64-e3e6f11b3f04.jpeg)

**Comment by GMSyrimis** [comment]
Hi, unfortunately, we do not officially support Ionic applications 😞
